language: android
jdk:
    - oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-26.0.1
        - android-26
        - android-14
        - extra-android-m2repository
        - extra-android-support

script: ./gradlew check
